### ISSUE TITLE
Remove the local package installation in requirements.txt 

### ISSUE THREAD

**Issue by Danselem** [rfinn/python-intermediate-inflammation#9]
Update your requirements.txt file and remove the local package installation in line 5.
- `-e git+https://github.com/rfinn/python-intermediate-inflammation.git@5c183508e503f8eb01fff7ad7ab8ebb245162ba9#egg=inflammation_analysis`

**Comment by rfinn** [comment]
we tried setting up the repository on Alex's machine, and there was not error when using the requirements.txt file as given.  We are therefore closing the issue.
